on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lionel-rigoux/pandemics-action@ac0b91f2aace3ea55cf8cfade1cedd9390651294
        with:
          source: report.md
